AuthorBundle\Entity\Author:
    type: entity
    repositoryClass: AuthorBundle\Entity\Repository\AuthorRepository
    table: author
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        articles:
            targetEntity: ArticleBundle\Entity\Article
            mappedBy: authors