AuthorBundle\Entity\Author:
    type: entity
    repositoryClass: AuthorBundle\Entity\Repository\AuthorRepository
    table: author
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        articles:
            targetEntity: ArticleBundle\Entity\Article
            inversedBy: authors
            joinTable:
                name: authorArticle
                joinColumns:
                    authorId:
                        referencedColumnName: id
                inverseJoinColumns:
                    articleId:
                        referencedColumnName: id
                        unique: true
            cascade:
                [ "persist", "remove" ]
            orphanRemoval: true
