ArticleBundle\Entity\Article:
    type: entity
    repositoryClass: ArticleBundle\Entity\Repository\ArticleRepository
    table: article
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 191
            unique: true
            nullable: true
        content:
            type: text
            nullable: true
        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: update
    manyToMany:
        authors:
            targetEntity: AuthorBundle\Entity\Author
            mappedBy: articles